export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const GET_LINKS_REQUEST = 'GET_LINKS_REQUEST';
export const SAVE_LINK_REQUEST = 'SAVE_LINK_REQUEST';
export const UPDATE_LINK_REQUEST = 'UPDATE_LINK_REQUEST';
export const DELETE_LINK_REQUEST = 'DELETE_LINK_REQUEST';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_LINKS_SUCCESS = 'GET_LINKS_SUCCESS';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const GET_LINKS_FAILURE = 'GET_LINKS_FAILURE';

export const SELECT_LINK = 'SELECT_LINK';
export const CREATE_LINK = 'CREATE_LINK';
export const RESET_LINK = 'RESET_LINK';
export const TOGGLE_DELETE_MODE = 'TOGGLE_DELETE_MODE';
