export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const GET_LINKS_REQUEST = 'GET_LINKS_REQUEST';
export const CREATE_LINK_REQUEST = 'CREATE_LINK_REQUEST';
export const UPDATE_LINK_REQUEST = 'UPDATE_LINK_REQUEST';
export const DELETE_LINK_REQUEST = 'DELETE_LINK_REQUEST';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_LINKS_SUCCESS = 'GET_LINKS_SUCCESS';
export const CREATE_LINK_SUCCESS = 'CREATE_LINK_SUCCESS';
export const UPDATE_LINK_SUCCESS = 'UPDATE_LINK_SUCCESS';
export const DELETE_LINK_SUCCESS = 'DELETE_LINK_SUCCESS';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const GET_LINKS_FAILURE = 'GET_LINKS_FAILURE';
export const CREATE_LINK_FAILURE = 'CREATE_LINK_FAILURE';
export const UPDATE_LINK_FAILURE = 'UPDATE_LINK_FAILURE';
export const DELETE_LINK_FAILURE = 'DELETE_LINK_FAILURE';

export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const SELECT_LINK = 'SELECT_LINK';
export const CREATE_LINK = 'CREATE_LINK';
export const RESET_LINK = 'RESET_LINK';
export const TOGGLE_DELETE_MODE = 'TOGGLE_DELETE_MODE';
